### PR TITLE
Update errands screenshot

### PR DESCRIPTION
**Pull request by xtreme-matthew-smith**
To show new Ops Manager dropdown menu.

### CODE REVIEW

**Comment by AmberAlston** [comment]
That newer screenshot is Ops Man 1.11 isn't it? That's not appropriate to change for the currently released version of JMX Bridge v1.8. It only works with 1.8-1.10 ops man (1.10 sill looks like the existing screenshot). This is what the new errands screenshot should look like for v1.9 coming out for 1.11. Those docs are still to be updated.

**Comment by jncd** [comment]
@xtreme-matthew-smith Hi Matthew Smith! would you take a look at Amber's message and replace the screenshot if nec?  TIA, jane

**Comment by xtreme-matthew-smith** [comment]
I took a screenshot of the versions:

[image: image.png]

**Comment by jncd** [comment]
@xtreme-matthew-smith Much thanks. And for adding the 1-pixel border to the image too!

**Pull request merged**
